/* nehne調香ノート 素材データ (v1.5.2: 系統8分類・詳細はfamily_detailに保持)
   素材の追加・修正はこのファイルを差し替えるだけでOK */
const BASE_MATERIALS = [
 {
  "name": "Agar wood",
  "note": "Base",
  "family": "ウッディ",
  "desc": "濃厚でアニマリック、バルサミックなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、アニマリック、バルサミック",
  "vocab_fr": "Boisé, Animalique, Balsamique",
  "components": "アガロスピロール、ジンコホール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Rich, animalic and balsamic woody scent",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Animalic, Balsamic",
  "family_detail": "Woody",
  "components_en": "Agarospirol, Jinkoh-eremol"
 },
 {
  "name": "Ambrette Seed",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "植物性のムスク香、フローラルでわずかにフルーティ",
  "ifra": "制限なし",
  "vocab_ja": "ムスキー、パウダリー、フローラル",
  "vocab_fr": "Musqué, Poudré, Floral",
  "components": "アンブレットリド、ファルネソール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Plant-derived musk, floral with a hint of fruitiness",
  "ifra_en": "No restriction",
  "vocab_en": "Musky, Powdery, Floral",
  "family_detail": "Musky",
  "components_en": "Ambrettolide, Farnesol"
 },
 {
  "name": "Angelica root",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "アーシーでムスキー、ペッパーのようなスパイシーさ",
  "ifra": "0.8 光毒性",
  "vocab_ja": "アーシー、ムスキー、スパイシー",
  "vocab_fr": "Terreux, Musqué, Épicé",
  "components": "シクロペンタデカノリド、α-ピネン",
  "sg": 0.82,
  "defaultDilution": 10.0,
  "desc_en": "Earthy, musky, with a peppery spiciness",
  "ifra_en": "0.8% Phototoxicity",
  "vocab_en": "Earthy, Musky, Spicy",
  "family_detail": "Musky / Woody",
  "components_en": "Cyclopentadecanolide, alpha-Pinene"
 },
 {
  "name": "Basillic",
  "note": "Top",
  "family": "ハーバル",
  "desc": "アニスに似たフレッシュでスパイシーなグリーン香",
  "ifra": "3.4 エストラゴール制限",
  "vocab_ja": "ハーバル、スパイシー、アニス",
  "vocab_fr": "Herbacé, Épicé, Anisé",
  "components": "エストラゴール、リナロール、オイゲノール",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, spicy green scent reminiscent of anise",
  "ifra_en": "3.4% Estragole restriction",
  "vocab_en": "Herbal, Spicy, Anise",
  "family_detail": "Aromatic",
  "components_en": "Estragole, Linalool, Eugenol"
 },
 {
  "name": "Benzoin Abs",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "甘くバニラのようなパウダリーな樹脂の香り",
  "ifra": "制限なし",
  "vocab_ja": "バルサミック、スウィート、バニラ",
  "vocab_fr": "Balsamique, Doux, Vanillé",
  "components": "安息香酸、ケイ皮酸、バニリン",
  "sg": 1.13,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, vanilla-like powdery resin scent",
  "ifra_en": "No restriction",
  "vocab_en": "Balsamic, Sweet, Vanilla",
  "family_detail": "Balsamic",
  "components_en": "Benzoic acid, Cinnamic acid, Vanillin"
 },
 {
  "name": "Bergamot",
  "note": "Top",
  "family": "シトラス",
  "desc": "フレッシュでフルーティ、わずかにフローラルな柑橘香",
  "ifra": "0.4 光毒性(Expressed)",
  "vocab_ja": "シトラス、ゼスティ、フローラル",
  "vocab_fr": "Hespéridé, Zesté, Floral",
  "components": "酢酸リナリル、リモネン、リナロール",
  "sg": 0.87,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, fruity citrus with a touch of floralcy",
  "ifra_en": "0.4% Phototoxicity (expressed oil)",
  "vocab_en": "Citrus, Zesty, Floral",
  "family_detail": "Citrus",
  "components_en": "Linalyl acetate, Limonene, Linalool"
 },
 {
  "name": "Birch tar",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "スモーキーでタールのような強いレザー香",
  "ifra": "0.16 皮膚感作性",
  "vocab_ja": "レザー、スモーキー、タール",
  "vocab_fr": "Cuiré, Fumé, Goudron",
  "components": "クレゾール、フェノール類",
  "sg": 0.96,
  "defaultDilution": 10.0,
  "desc_en": "Smoky, tar-like intense leather scent",
  "ifra_en": "0.16% Skin sensitization",
  "vocab_en": "Leather, Smoky, Tar",
  "family_detail": "Leather",
  "components_en": "Cresol, Phenols"
 },
 {
  "name": "Bitter orange",
  "note": "Top",
  "family": "シトラス",
  "desc": "爽やかでドライ、わずかに苦味のある柑橘香",
  "ifra": "1.25 光毒性",
  "vocab_ja": "シトラス、ビター、ピール",
  "vocab_fr": "Hespéridé, Amer, Zeste",
  "components": "リモネン、リナロール、ミルセン",
  "sg": 0.9,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, dry citrus with a hint of bitterness",
  "ifra_en": "1.25% Phototoxicity",
  "vocab_en": "Citrus, Bitter, Peel",
  "family_detail": "Citrus",
  "components_en": "Limonene, Linalool, Myrcene"
 },
 {
  "name": "Black carrant",
  "note": "Top",
  "family": "グリーン・フルーティー",
  "desc": "非常に強いグリーンでフルーティ、わずかにアニマリック",
  "ifra": "制限なし",
  "vocab_ja": "フルーティ、グリーン、サルファリック",
  "vocab_fr": "Fruité, Vert, Sulfurique",
  "components": "チオメンタン類、p-メンタン-8-チオール-3-オン",
  "sg": 0.98,
  "defaultDilution": 10.0,
  "desc_en": "Very strong green, fruity, slightly animalic",
  "ifra_en": "No restriction",
  "vocab_en": "Fruity, Green, Sulfurous",
  "family_detail": "Fruity / Green",
  "components_en": "Thiomenthanes, p-Menthane-8-thiol-3-one"
 },
 {
  "name": "Black pepper",
  "note": "Top",
  "family": "スパイシー",
  "desc": "ドライで温かみのあるシャープなスパイス香",
  "ifra": "制限なし",
  "vocab_ja": "スパイシー、ピカント、ウッディ",
  "vocab_fr": "Épicé, Piquant, Boisé",
  "components": "ピペリン、カリオフィレン、リモネン",
  "sg": 1.02,
  "defaultDilution": 10.0,
  "desc_en": "Dry, warm, sharp spice scent",
  "ifra_en": "No restriction",
  "vocab_en": "Spicy, Piquant, Woody",
  "family_detail": "Spicy",
  "components_en": "Piperine, Caryophyllene, Limonene"
 },
 {
  "name": "Camomile German Blue",
  "note": "Middle",
  "family": "フローラル",
  "desc": "甘くフルーティでハーブのような温かみのある香り",
  "ifra": "制限なし",
  "vocab_ja": "ハーバル、フルーティ、カモミール",
  "vocab_fr": "Herbacé, Fruité, Camomille",
  "components": "カマズレン、ビサボロール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, fruity, warm herbal scent",
  "ifra_en": "No restriction",
  "vocab_en": "Herbal, Fruity, Chamomile",
  "family_detail": "Floral / Herbal",
  "components_en": "Chamazulene, Bisabolol"
 },
 {
  "name": "Camomille Roman",
  "note": "Middle",
  "family": "フローラル",
  "desc": "青リンゴのような甘くフレッシュなハーブ香",
  "ifra": "制限なし",
  "vocab_ja": "ハーバル、アップル、スウィート",
  "vocab_fr": "Herbacé, Pomme, Doux",
  "components": "アンゲリカ酸エステル類、チグリン酸エステル",
  "sg": 0.89,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, fresh herbal scent like green apple",
  "ifra_en": "No restriction",
  "vocab_en": "Herbal, Apple, Sweet",
  "family_detail": "Floral / Herbal",
  "components_en": "Angelate esters, Tiglate esters"
 },
 {
  "name": "Caldamon",
  "note": "Top",
  "family": "スパイシー",
  "desc": "爽快でカンファー調の甘くスパイシーな香り",
  "ifra": "制限なし",
  "vocab_ja": "スパイシー、カンファー、フレッシュ",
  "vocab_fr": "Épicé, Camphré, Frais",
  "components": "酢酸テルピニル、1,8-シネオール、α-テルピネオール",
  "sg": 0.92,
  "defaultDilution": 10.0,
  "desc_en": "Refreshing, camphoraceous, sweet spicy scent",
  "ifra_en": "No restriction",
  "vocab_en": "Spicy, Camphor, Fresh",
  "family_detail": "Spicy",
  "components_en": "Terpinyl acetate, 1,8-Cineole, alpha-Terpineol"
 },
 {
  "name": "Carrot seed",
  "note": "Middle",
  "family": "バルサム・レジン",
  "desc": "土っぽくウッディで、アイリスに似たパウダリー香",
  "ifra": "制限なし",
  "vocab_ja": "アーシー、パウダリー、ウッディ",
  "vocab_fr": "Terreux, Poudré, Boisé",
  "components": "カロトール、ダウコール",
  "sg": 0.94,
  "defaultDilution": 10.0,
  "desc_en": "Earthy, woody, powdery scent reminiscent of iris",
  "ifra_en": "No restriction",
  "vocab_en": "Earthy, Powdery, Woody",
  "family_detail": "Powdery / Earthy",
  "components_en": "Carotol, Daucol"
 },
 {
  "name": "Cassis Bud Abs",
  "note": "Top",
  "family": "グリーン・フルーティー",
  "desc": "硫黄のような鋭いグリーンと濃厚なフルーティ香",
  "ifra": "制限なし",
  "vocab_ja": "グリーン、フルーティ、アニマリック",
  "vocab_fr": "Vert, Fruité, Animalique",
  "components": "チオメンタン類",
  "sg": 0.98,
  "defaultDilution": 10.0,
  "desc_en": "Sharp sulfurous green with rich fruitiness",
  "ifra_en": "No restriction",
  "vocab_en": "Green, Fruity, Animalic",
  "family_detail": "Green / Fruity",
  "components_en": "Thiomenthanes"
 },
 {
  "name": "Cederwood atras",
  "note": "Base",
  "family": "ウッディ",
  "desc": "暖かく甘い、少しカンファー調のウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、カンファー、スウィート",
  "vocab_fr": "Boisé, Camphré, Doux",
  "components": "α-アトラントン、セドロール",
  "sg": 0.93,
  "defaultDilution": 10.0,
  "desc_en": "Warm, sweet, slightly camphoraceous woody scent",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Camphor, Sweet",
  "family_detail": "Woody",
  "components_en": "alpha-Atlantone, Cedrol"
 },
 {
  "name": "Cederwood texas",
  "note": "Base",
  "family": "ウッディ",
  "desc": "ドライでスモーキーなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、ドライ、スモーキー",
  "vocab_fr": "Boisé, Sec, Fumé",
  "components": "セドロール、ツヨプセン",
  "sg": 0.95,
  "defaultDilution": 10.0,
  "desc_en": "Dry, smoky woody scent",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Dry, Smoky",
  "family_detail": "Woody",
  "components_en": "Cedrol, Thujopsene"
 },
 {
  "name": "Cederwood virginia",
  "note": "Base",
  "family": "ウッディ",
  "desc": "鉛筆の削りかすのようなドライでクリーンな木材の香り",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、ドライ、ペンシル",
  "vocab_fr": "Boisé, Sec, Crayon",
  "components": "セドロール、セドレン",
  "sg": 0.96,
  "defaultDilution": 10.0,
  "desc_en": "Dry, clean wood scent like pencil shavings",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Dry, Pencil",
  "family_detail": "Woody",
  "components_en": "Cedrol, Cedrene"
 },
 {
  "name": "Celery seed",
  "note": "Top",
  "family": "スパイシー",
  "desc": "スープのような温かくスパイシーでアーシーな香り",
  "ifra": "制限なし",
  "vocab_ja": "スパイシー、アーシー、ベジタル",
  "vocab_fr": "Épicé, Terreux, Végétal",
  "components": "セダノリド、リモネン",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Warm, spicy, earthy scent like soup",
  "ifra_en": "No restriction",
  "vocab_en": "Spicy, Earthy, Vegetal",
  "family_detail": "Spicy",
  "components_en": "Sedanolide, Limonene"
 },
 {
  "name": "Clary sage",
  "note": "Middle",
  "family": "ハーバル",
  "desc": "甘くハーブ調で、ティーやタバコのようなニュアンス",
  "ifra": "制限なし",
  "vocab_ja": "ハーバル、ティー、アンバリー",
  "vocab_fr": "Herbacé, Thé, Ambré",
  "components": "酢酸リナリル、リナロール、スクラレオール",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, herbal, with tea and tobacco nuances",
  "ifra_en": "No restriction",
  "vocab_en": "Herbal, Tea, Ambery",
  "family_detail": "Aromatic",
  "components_en": "Linalyl acetate, Linalool, Sclareol"
 },
 {
  "name": "Clove Bud",
  "note": "Middle",
  "family": "スパイシー",
  "desc": "強く甘い、カーネーションに似たスパイス香",
  "ifra": "0.5 オイゲノール制限",
  "vocab_ja": "スパイシー、スウィート、メディシナル",
  "vocab_fr": "Épicé, Doux, Médicinal",
  "components": "オイゲノール、酢酸オイゲニル、カリオフィレン",
  "sg": 1.03,
  "defaultDilution": 10.0,
  "desc_en": "Strong, sweet spice scent resembling carnation",
  "ifra_en": "0.5% Eugenol restriction",
  "vocab_en": "Spicy, Sweet, Medicinal",
  "family_detail": "Spicy",
  "components_en": "Eugenol, Eugenyl acetate, Caryophyllene"
 },
 {
  "name": "Coriander seed",
  "note": "Top",
  "family": "スパイシー",
  "desc": "スパイシーでウッディ、フローラルなニュアンス",
  "ifra": "制限なし",
  "vocab_ja": "スパイシー、フローラル、ウッディ",
  "vocab_fr": "Épicé, Floral, Boisé",
  "components": "リナロール（コリアンドロール）、ピネン",
  "sg": 0.86,
  "defaultDilution": 10.0,
  "desc_en": "Spicy, woody, with floral nuances",
  "ifra_en": "No restriction",
  "vocab_en": "Spicy, Floral, Woody",
  "family_detail": "Spicy",
  "components_en": "Linalool (coriandrol), Pinene"
 },
 {
  "name": "Cumin",
  "note": "Top",
  "family": "スパイシー",
  "desc": "非常に強くアニマリックで温かいスパイス香",
  "ifra": "0.4 光毒性",
  "vocab_ja": "スパイシー、アニマリック、ウォーム",
  "vocab_fr": "Épicé, Animalique, Chaud",
  "components": "クミンアルデヒド、ピネン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Very strong, animalic, warm spice scent",
  "ifra_en": "0.4% Phototoxicity",
  "vocab_en": "Spicy, Animalic, Warm",
  "family_detail": "Spicy",
  "components_en": "Cuminaldehyde, Pinene"
 },
 {
  "name": "Cypres",
  "note": "Middle",
  "family": "ウッディ",
  "desc": "フレッシュで松脂のようなウッディ・バルサミック香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、レジナス、パイン",
  "vocab_fr": "Boisé, Résineux, Pin",
  "components": "α-ピネン、δ-3-カレン",
  "sg": 0.83,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, woody-balsamic scent like pine resin",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Resinous, Pine",
  "family_detail": "Woody",
  "components_en": "alpha-Pinene, delta-3-Carene"
 },
 {
  "name": "Dabana",
  "note": "Middle",
  "family": "グリーン・フルーティー",
  "desc": "洋酒やドライフルーツのような甘く濃厚な香り",
  "ifra": "0.7 光毒性",
  "vocab_ja": "フルーティ、リキュール、バルサミック",
  "vocab_fr": "Fruité, Liqueur, Balsamique",
  "components": "ダバノン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, rich scent like liqueur or dried fruit",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Fruity, Liqueur, Balsamic",
  "family_detail": "Fruity / Balsamic",
  "components_en": "Davanone"
 },
 {
  "name": "Euclyptus blue mallee",
  "note": "Top",
  "family": "ハーバル",
  "desc": "非常に強くフレッシュなカンファー（樟脳）香",
  "ifra": "制限なし",
  "vocab_ja": "カンファー、フレッシュ、メディシナル",
  "vocab_fr": "Camphré, Frais, Médicinal",
  "components": "1,8-シネオール、α-ピネン、リモネン",
  "sg": 0.91,
  "defaultDilution": 10.0,
  "desc_en": "Very strong, fresh camphoraceous scent",
  "ifra_en": "No restriction",
  "vocab_en": "Camphor, Fresh, Medicinal",
  "family_detail": "Aromatic",
  "components_en": "1,8-Cineole, alpha-Pinene, Limonene"
 },
 {
  "name": "Euclyptus dives",
  "note": "Top",
  "family": "ハーバル",
  "desc": "ペパーミントに似たフレッシュで鋭い香り",
  "ifra": "制限なし",
  "vocab_ja": "ミント、カンファー、フレッシュ",
  "vocab_fr": "Mentholé, Camphré, Frais",
  "components": "ピペリトン、フェランドレン",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, sharp scent similar to peppermint",
  "ifra_en": "No restriction",
  "vocab_en": "Minty, Camphor, Fresh",
  "family_detail": "Aromatic",
  "components_en": "Piperitone, Phellandrene"
 },
 {
  "name": "Euclyptus globuls",
  "note": "Top",
  "family": "ハーバル",
  "desc": "典型的なフレッシュでクリアなユーカリ香",
  "ifra": "制限なし",
  "vocab_ja": "カンファー、フレッシュ、クリア",
  "vocab_fr": "Camphré, Frais, Clair",
  "components": "1,8-シネオール、α-ピネン、リモネン",
  "sg": 0.9,
  "defaultDilution": 10.0,
  "desc_en": "Typical fresh, clear eucalyptus scent",
  "ifra_en": "No restriction",
  "vocab_en": "Camphor, Fresh, Clear",
  "family_detail": "Aromatic",
  "components_en": "1,8-Cineole, alpha-Pinene, Limonene"
 },
 {
  "name": "Euclyptus lemon",
  "note": "Top",
  "family": "シトラス",
  "desc": "強いレモン調のフレッシュな香り",
  "ifra": "0.57 シトラール等制限",
  "vocab_ja": "シトラス、レモン、フレッシュ",
  "vocab_fr": "Hespéridé, Citronné, Frais",
  "components": "シトロネラール、シトロネロール",
  "sg": 0.85,
  "defaultDilution": 10.0,
  "desc_en": "Strong, fresh lemon-toned scent",
  "ifra_en": "0.57% Citral (and related) restriction",
  "vocab_en": "Citrus, Lemon, Fresh",
  "family_detail": "Citrus / Aromatic",
  "components_en": "Citronellal, Citronellol"
 },
 {
  "name": "Frankinsence",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "スパイシーでレモンのような爽やかさを持つ樹脂香",
  "ifra": "制限なし",
  "vocab_ja": "バルサミック、インセンス、ゼスティ",
  "vocab_fr": "Balsamique, Encens, Zesté",
  "components": "α-ピネン、オリバノール",
  "sg": 0.84,
  "defaultDilution": 10.0,
  "desc_en": "Spicy resin scent with a lemony freshness",
  "ifra_en": "No restriction",
  "vocab_en": "Balsamic, Incense, Zesty",
  "family_detail": "Balsamic / Woody",
  "components_en": "alpha-Pinene, Olibanol"
 },
 {
  "name": "Galangal",
  "note": "Top",
  "family": "スパイシー",
  "desc": "ジンジャーに似た温かくスパイシーな香り",
  "ifra": "0.7 光毒性",
  "vocab_ja": "スパイシー、ジンジャー、ウォーム",
  "vocab_fr": "Épicé, Gingembre, Chaud",
  "components": "シネオール、ピネン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Warm, spicy scent similar to ginger",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Spicy, Ginger, Warm",
  "family_detail": "Spicy",
  "components_en": "Cineole, Pinene"
 },
 {
  "name": "Galbanum",
  "note": "Top",
  "family": "グリーン・フルーティー",
  "desc": "鋭く土っぽい、非常に強いフレッシュグリーン香",
  "ifra": "制限なし",
  "vocab_ja": "グリーン、アーシー、ペネトレーティング",
  "vocab_fr": "Vert, Terreux, Pénétrant",
  "components": "ウンデカトリエン、ピネン",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Sharp, earthy, very strong fresh green scent",
  "ifra_en": "No restriction",
  "vocab_en": "Green, Earthy, Penetrating",
  "family_detail": "Green",
  "components_en": "Undecatriene, Pinene"
 },
 {
  "name": "Ginger abs",
  "note": "Top",
  "family": "スパイシー",
  "desc": "温かくウッディで、ピリッとしたスパイス香",
  "ifra": "制限なし",
  "vocab_ja": "スパイシー、ウォーム、ウッディ",
  "vocab_fr": "Épicé, Chaud, Boisé",
  "components": "ジンギベレン、ジンゲロール、ショウガオール",
  "sg": 0.9,
  "defaultDilution": 10.0,
  "desc_en": "Warm, woody, pungent spice scent",
  "ifra_en": "No restriction",
  "vocab_en": "Spicy, Warm, Woody",
  "family_detail": "Spicy",
  "components_en": "Zingiberene, Gingerol, Shogaol"
 },
 {
  "name": "Grape fruit",
  "note": "Top",
  "family": "シトラス",
  "desc": "爽やかでほのかに苦い、フレッシュな柑橘香",
  "ifra": "4 光毒性",
  "vocab_ja": "シトラス、ビター、ジューシー",
  "vocab_fr": "Hespéridé, Amer, Juteux",
  "components": "リモネン、ヌートカトン、グレープフルーツメルカプタン",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, faintly bitter citrus scent",
  "ifra_en": "4% Phototoxicity",
  "vocab_en": "Citrus, Bitter, Juicy",
  "family_detail": "Citrus",
  "components_en": "Limonene, Nootkatone, Grapefruit mercaptan"
 },
 {
  "name": "Guaiac Wood",
  "note": "Base",
  "family": "ウッディ",
  "desc": "バラのような甘さとスモーキーさを持つウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、スウィート、スモーキー",
  "vocab_fr": "Boisé, Doux, Fumé",
  "components": "グアイオール、ブルネソール",
  "sg": 0.94,
  "defaultDilution": 10.0,
  "desc_en": "Woody scent with rose-like sweetness and smokiness",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Sweet, Smoky",
  "family_detail": "Woody",
  "components_en": "Guaiol, Brunesol"
 },
 {
  "name": "Hay Abs 90%",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "干し草の甘く温かいクマリン調の香り",
  "ifra": "クマリン合算注意",
  "vocab_ja": "スウィート、ヘイ、クマリン",
  "vocab_fr": "Doux, Foin, Coumarine",
  "components": "クマリン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, warm coumarin-like scent of dried hay",
  "ifra_en": "Coumarin cumulative-total caution",
  "vocab_en": "Sweet, Hay, Coumarin",
  "family_detail": "Fougère / Sweet",
  "components_en": "Coumarin"
 },
 {
  "name": "Ho wood",
  "note": "Middle",
  "family": "ウッディ",
  "desc": "リナロールを豊富に含む、甘くフローラルなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、フローラル、スウィート",
  "vocab_fr": "Boisé, Floral, Doux",
  "components": "リナロール、カンファー",
  "sg": 0.86,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, floral woody scent rich in linalool",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Floral, Sweet",
  "family_detail": "Woody / Floral",
  "components_en": "Linalool, Camphor"
 },
 {
  "name": "Inula",
  "note": "Middle",
  "family": "ハーバル",
  "desc": "カンファー調の強いハーブ香",
  "ifra": "0 IFRA禁止/極めて厳しい",
  "vocab_ja": "ハーバル、カンファー、ストロング",
  "vocab_fr": "Herbacé, Camphré, Fort",
  "components": "ボルネオール、カンファー",
  "sg": 0.94,
  "defaultDilution": 10.0,
  "desc_en": "Strong herbal scent with a camphoraceous tone",
  "ifra_en": "0% IFRA prohibited / extremely restricted",
  "vocab_en": "Herbal, Camphor, Strong",
  "family_detail": "Herbal",
  "components_en": "Borneol, Camphor"
 },
 {
  "name": "Jasmin Grandiflorum Abs",
  "note": "Middle",
  "family": "フローラル",
  "desc": "濃厚で甘く、アニマリックなホワイトフローラル香",
  "ifra": "0.6 皮膚感作性",
  "vocab_ja": "フローラル、アニマリック、ジャスミン",
  "vocab_fr": "Floral, Animalique, Jasminé",
  "components": "酢酸ベンジル、リナロール、インドール、ジャスモン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Rich, sweet, animalic white floral scent",
  "ifra_en": "0.6% Skin sensitization",
  "vocab_en": "Floral, Animalic, Jasmine",
  "family_detail": "Floral",
  "components_en": "Benzyl acetate, Linalool, Indole, Jasmone"
 },
 {
  "name": "Juniper berry",
  "note": "Top",
  "family": "ハーバル",
  "desc": "ジンのようなフレッシュでウッディな松のような香り",
  "ifra": "制限なし",
  "vocab_ja": "フレッシュ、パイン、ジニー",
  "vocab_fr": "Frais, Pin, Genièvre",
  "components": "α-ピネン、ミルセン、サビネン",
  "sg": 0.84,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, woody, pine-like scent reminiscent of gin",
  "ifra_en": "No restriction",
  "vocab_en": "Fresh, Pine, Gin-like",
  "family_detail": "Aromatic",
  "components_en": "alpha-Pinene, Myrcene, Sabinene"
 },
 {
  "name": "Kouchi konatsu",
  "note": "Top",
  "family": "シトラス",
  "desc": "日本特有の爽やかでジューシーな柑橘香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "シトラス、ジューシー、フレッシュ",
  "vocab_fr": "Hespéridé, Juteux, Frais",
  "components": "リモネン、テルピネオール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, juicy citrus scent distinctive to Japan",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Citrus, Juicy, Fresh",
  "family_detail": "Citrus",
  "components_en": "Limonene, Terpineol"
 },
 {
  "name": "Labdanum Abs 85%",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "アンバーに似た甘く温かい、レザーやハチミツの香り",
  "ifra": "制限なし",
  "vocab_ja": "バルサミック、アンバリー、レザー",
  "vocab_fr": "Balsamique, Ambré, Cuiré",
  "components": "ピネン、カンフェン、ラブダノイル類",
  "sg": 0.91,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, warm amber-like scent with leather and honey",
  "ifra_en": "No restriction",
  "vocab_en": "Balsamic, Ambery, Leather",
  "family_detail": "Balsamic",
  "components_en": "Pinene, Camphene, Labdanoids"
 },
 {
  "name": "Lavender",
  "note": "Top",
  "family": "フローラル",
  "desc": "フレッシュでハーブ調のフローラル香",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、ハーバル、フレッシュ",
  "vocab_fr": "Floral, Herbacé, Frais",
  "components": "酢酸リナリル、リナロール",
  "sg": 0.89,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, herbal floral scent",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Herbal, Fresh",
  "family_detail": "Floral / Aromatic",
  "components_en": "Linalyl acetate, Linalool"
 },
 {
  "name": "Lavender 40/42",
  "note": "Top",
  "family": "フローラル",
  "desc": "標準化された、甘くフローラルなラベンダー香",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、ハーバル、スウィート",
  "vocab_fr": "Floral, Herbacé, Doux",
  "components": "酢酸リナリル（40-42%）、リナロール",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Standardized, sweet floral lavender scent",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Herbal, Sweet",
  "family_detail": "Floral / Aromatic",
  "components_en": "Linalyl acetate (40-42%), Linalool"
 },
 {
  "name": "Lemon",
  "note": "Top",
  "family": "シトラス",
  "desc": "非常にフレッシュで鋭い、ジューシーな柑橘香",
  "ifra": "2 光毒性",
  "vocab_ja": "シトラス、ゼスティ、フレッシュ",
  "vocab_fr": "Hespéridé, Zesté, Frais",
  "components": "リモネン、シトラール、ピネン",
  "sg": 0.85,
  "defaultDilution": 10.0,
  "desc_en": "Very fresh, sharp, juicy citrus scent",
  "ifra_en": "2% Phototoxicity",
  "vocab_en": "Citrus, Zesty, Fresh",
  "family_detail": "Citrus",
  "components_en": "Limonene, Citral, Pinene"
 },
 {
  "name": "Lemon grass",
  "note": "Top",
  "family": "シトラス",
  "desc": "レモンのような力強いグリーン・ハーブ香",
  "ifra": "0.6 シトラール制限",
  "vocab_ja": "シトラス、グリーン、ハーバル",
  "vocab_fr": "Hespéridé, Vert, Herbacé",
  "components": "シトラール（ゲラニアール、ネラール）",
  "sg": 0.9,
  "defaultDilution": 10.0,
  "desc_en": "Strong lemon-like green herbal scent",
  "ifra_en": "0.6% Citral restriction",
  "vocab_en": "Citrus, Green, Herbal",
  "family_detail": "Citrus / Green",
  "components_en": "Citral (geranial, neral)"
 },
 {
  "name": "Lemon myrtre",
  "note": "Top",
  "family": "シトラス",
  "desc": "レモングラスより甘く濃厚なシトラス香",
  "ifra": "0.6 シトラール制限",
  "vocab_ja": "シトラス、スウィート、インテンス",
  "vocab_fr": "Hespéridé, Doux, Intense",
  "components": "シトラール",
  "sg": 0.88,
  "defaultDilution": 10.0,
  "desc_en": "Sweeter, more intense citrus than lemongrass",
  "ifra_en": "0.6% Citral restriction",
  "vocab_en": "Citrus, Sweet, Intense",
  "family_detail": "Citrus",
  "components_en": "Citral"
 },
 {
  "name": "Lime",
  "note": "Top",
  "family": "シトラス",
  "desc": "ドライでシャープ、少し甘みのある柑橘香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "シトラス、シャープ、ドライ",
  "vocab_fr": "Hespéridé, Acide, Sec",
  "components": "リモネン、γ-テルピネン、シトラール",
  "sg": 0.85,
  "defaultDilution": 10.0,
  "desc_en": "Dry, sharp citrus with a hint of sweetness",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Citrus, Sharp, Dry",
  "family_detail": "Citrus",
  "components_en": "Limonene, gamma-Terpinene, Citral"
 },
 {
  "name": "Linden blossom",
  "note": "Middle",
  "family": "フローラル",
  "desc": "ハチミツのように甘く温かいフローラル香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "フローラル、ハニー、スウィート",
  "vocab_fr": "Floral, Miel, Doux",
  "components": "ファルネソール、リナロール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, warm floral scent like honey",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Floral, Honey, Sweet",
  "family_detail": "Floral",
  "components_en": "Farnesol, Linalool"
 },
 {
  "name": "Marigold tagetes",
  "note": "Middle",
  "family": "グリーン・フルーティー",
  "desc": "非常に強くフルーティでグリーンなリンゴのような香り",
  "ifra": "0.01 光毒性",
  "vocab_ja": "グリーン、フルーティ、アップル",
  "vocab_fr": "Vert, Fruité, Pomme",
  "components": "タゲトン、オシメン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Very strong fruity green scent like apple",
  "ifra_en": "0.01% Phototoxicity",
  "vocab_en": "Green, Fruity, Apple",
  "family_detail": "Green / Floral",
  "components_en": "Tagetone, Ocimene"
 },
 {
  "name": "Mandarin Orange",
  "note": "Top",
  "family": "シトラス",
  "desc": "非常に甘くフルーティな柑橘香",
  "ifra": "制限なし",
  "vocab_ja": "シトラス、スウィート、フルーティ",
  "vocab_fr": "Hespéridé, Doux, Fruité",
  "components": "リモネン、γ-テルピネン、アントラニル酸ジメチル",
  "sg": 0.84,
  "defaultDilution": 10.0,
  "desc_en": "Very sweet, fruity citrus scent",
  "ifra_en": "No restriction",
  "vocab_en": "Citrus, Sweet, Fruity",
  "family_detail": "Citrus",
  "components_en": "Limonene, gamma-Terpinene, Dimethyl anthranilate"
 },
 {
  "name": "Meronal",
  "note": "Top",
  "family": "グリーン・フルーティー",
  "desc": "メロンやオゾンのようなみずみずしい香り（※合成香料系）",
  "ifra": "0.86 光毒性",
  "vocab_ja": "マリーン、メロン、オゾニック",
  "vocab_fr": "Marin, Melon, Ozonique",
  "components": "メロナール（2",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, watery scent of melon and ozone (synthetic)",
  "ifra_en": "0.86% Phototoxicity",
  "vocab_en": "Marine, Melon, Ozonic",
  "family_detail": "Marine / Melon",
  "components_en": "Melonal (2"
 },
 {
  "name": "Myrrh",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "温かくマッシュルームのような土っぽさを持つ樹脂香",
  "ifra": "制限なし",
  "vocab_ja": "バルサミック、アーシー、マッシュルーム",
  "vocab_fr": "Balsamique, Terreux, Champignon",
  "components": "フラノエウデスマ-1",
  "sg": 1.01,
  "defaultDilution": 10.0,
  "desc_en": "Warm, earthy resin scent reminiscent of mushroom",
  "ifra_en": "No restriction",
  "vocab_en": "Balsamic, Earthy, Mushroom",
  "family_detail": "Balsamic",
  "components_en": "Furanoeudesma-1"
 },
 {
  "name": "Neroli",
  "note": "Middle",
  "family": "フローラル",
  "desc": "フレッシュでグリーン、わずかに苦いオレンジの花の香り",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、グリーン、ビター",
  "vocab_fr": "Floral, Vert, Amer",
  "components": "リナロール、リモネン、ネロリドール",
  "sg": 0.85,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, green, slightly bitter orange blossom scent",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Green, Bitter",
  "family_detail": "Floral",
  "components_en": "Linalool, Limonene, Nerolidol"
 },
 {
  "name": "Oak moss",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "土っぽく湿った森、ウッディで重厚な香り",
  "ifra": "0.1 皮膚感作性",
  "vocab_ja": "モッシー、アーシー、ウッディ",
  "vocab_fr": "Mousse, Terreux, Boisé",
  "components": "エベルニン酸、アトラノール",
  "sg": 1.05,
  "defaultDilution": 10.0,
  "desc_en": "Earthy, damp-forest, heavy woody scent",
  "ifra_en": "0.1% Skin sensitization",
  "vocab_en": "Mossy, Earthy, Woody",
  "family_detail": "Mossy / Chypre",
  "components_en": "Evernic acid, Atranol"
 },
 {
  "name": "Okinawa gettou",
  "note": "Middle",
  "family": "ハーバル",
  "desc": "月桃特有のスパイシーで爽やかなハーブ香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "ハーバル、スパイシー、フレッシュ",
  "vocab_fr": "Herbacé, Épicé, Frais",
  "components": "1,8-シネオール、テルピネン-4-オール、カンファー",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Spicy, fresh herbal scent distinctive to gettou (shell ginger)",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Herbal, Spicy, Fresh",
  "family_detail": "Aromatic",
  "components_en": "1,8-Cineole, Terpinen-4-ol, Camphor"
 },
 {
  "name": "Opopanax",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "甘くスパイシーで、バルサミックな樹脂の香り",
  "ifra": "0.43 皮膚感作性",
  "vocab_ja": "バルサミック、スウィート、スパイシー",
  "vocab_fr": "Balsamique, Doux, Épicé",
  "components": "ビサボレン",
  "sg": 1.04,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, spicy, balsamic resin scent",
  "ifra_en": "0.43% Skin sensitization",
  "vocab_en": "Balsamic, Sweet, Spicy",
  "family_detail": "Balsamic",
  "components_en": "Bisabolene"
 },
 {
  "name": "Orange flower abs",
  "note": "Middle",
  "family": "フローラル",
  "desc": "非常に濃厚で甘くアニマリックなオレンジの花の香り",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、アニマリック、スウィート",
  "vocab_fr": "Floral, Animalique, Doux",
  "components": "リナロール、アントラニル酸メチル、インドール",
  "sg": 0.917,
  "defaultDilution": 10.0,
  "desc_en": "Very rich, sweet, animalic orange blossom scent",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Animalic, Sweet",
  "family_detail": "Floral",
  "components_en": "Linalool, Methyl anthranilate, Indole"
 },
 {
  "name": "Orange Sweet",
  "note": "Top",
  "family": "シトラス",
  "desc": "フレッシュで甘くジューシーなオレンジの香り",
  "ifra": "制限なし",
  "vocab_ja": "シトラス、スウィート、ジューシー",
  "vocab_fr": "Hespéridé, Doux, Juteux",
  "components": "リモネン、デカナール",
  "sg": 0.84,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, sweet, juicy orange scent",
  "ifra_en": "No restriction",
  "vocab_en": "Citrus, Sweet, Juicy",
  "family_detail": "Citrus",
  "components_en": "Limonene, Decanal"
 },
 {
  "name": "Orris root",
  "note": "Middle",
  "family": "バルサム・レジン",
  "desc": "バイオレットに似た非常に上品でパウダリーなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "パウダリー、バイオレット、ウッディ",
  "vocab_fr": "Poudré, Violette, Boisé",
  "components": "イロン",
  "sg": 0.93,
  "defaultDilution": 10.0,
  "desc_en": "Very elegant, powdery woody scent like violet",
  "ifra_en": "No restriction",
  "vocab_en": "Powdery, Violet, Woody",
  "family_detail": "Powdery",
  "components_en": "Irone"
 },
 {
  "name": "Osmanthus Abs",
  "note": "Middle",
  "family": "フローラル",
  "desc": "アプリコットやピーチに似た甘くフルーティな金木犀の香り",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、フルーティ、ピーチ",
  "vocab_fr": "Floral, Fruité, Pêche",
  "components": "β-イオノン、γ-デカラクトン、リナロール",
  "sg": 0.87,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, fruity osmanthus scent like apricot or peach",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Fruity, Peach",
  "family_detail": "Floral / Fruity",
  "components_en": "beta-Ionone, gamma-Decalactone, Linalool"
 },
 {
  "name": "Parmarosa",
  "note": "Middle",
  "family": "フローラル",
  "desc": "ローズに似た甘くフローラルでハーブ調の香り",
  "ifra": "ゲラニオール合算注意",
  "vocab_ja": "フローラル、ハーバル、ローズ",
  "vocab_fr": "Floral, Herbacé, Rosé",
  "components": "ゲラニオール、酢酸ゲラニル",
  "sg": 0.86,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, floral, herbal scent similar to rose",
  "ifra_en": "Geraniol cumulative-total caution",
  "vocab_en": "Floral, Herbal, Rose",
  "family_detail": "Floral",
  "components_en": "Geraniol, Geranyl acetate"
 },
 {
  "name": "Patchhouli",
  "note": "Base",
  "family": "ウッディ",
  "desc": "湿った土、木、わずかに甘いカンファー調の香り",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、アーシー、カンファー",
  "vocab_fr": "Boisé, Terreux, Camphré",
  "components": "パチュロール、ノルパチュレノール",
  "sg": 0.94,
  "defaultDilution": 10.0,
  "desc_en": "Damp earth and wood with a hint of sweet camphor",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Earthy, Camphor",
  "family_detail": "Woody",
  "components_en": "Patchoulol, Norpatchoulenol"
 },
 {
  "name": "Petitgrain",
  "note": "Top",
  "family": "シトラス",
  "desc": "オレンジの葉や枝からのシャープでドライなグリーン香",
  "ifra": "制限なし",
  "vocab_ja": "シトラス、グリーン、ドライ",
  "vocab_fr": "Hespéridé, Vert, Sec",
  "components": "酢酸リナリル、リナロール、テルピネオール",
  "sg": 0.87,
  "defaultDilution": 10.0,
  "desc_en": "Sharp, dry green scent from orange leaves and twigs",
  "ifra_en": "No restriction",
  "vocab_en": "Citrus, Green, Dry",
  "family_detail": "Citrus / Green",
  "components_en": "Linalyl acetate, Linalool, Terpineol"
 },
 {
  "name": "Pink Pepper corn",
  "note": "Top",
  "family": "スパイシー",
  "desc": "フレッシュでフルーティ、少しウッディなスパイス香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "スパイシー、フレッシュ、フルーティ",
  "vocab_fr": "Épicé, Frais, Fruité",
  "components": "α-フェランドレン、リモネン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, fruity, slightly woody spice scent",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Spicy, Fresh, Fruity",
  "family_detail": "Spicy",
  "components_en": "alpha-Phellandrene, Limonene"
 },
 {
  "name": "Rose Abs",
  "note": "Middle",
  "family": "フローラル",
  "desc": "濃厚で甘く、スパイシーさとハチミツのニュアンスを持つバラ香",
  "ifra": "2 メチルオイゲノール等制",
  "vocab_ja": "フローラル、スウィート、スパイシー",
  "vocab_fr": "Floral, Doux, Épicé",
  "components": "シトロネロール、ゲラニオール、フェニルエチルアルコール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Rich, sweet rose scent with spicy and honey nuances",
  "ifra_en": "2% Methyleugenol (and related) restriction",
  "vocab_en": "Floral, Sweet, Spicy",
  "family_detail": "Floral",
  "components_en": "Citronellol, Geraniol, Phenylethyl alcohol"
 },
 {
  "name": "Rose mary",
  "note": "Top",
  "family": "ハーバル",
  "desc": "フレッシュでカンファー調の強いハーブ香",
  "ifra": "制限なし",
  "vocab_ja": "ハーバル、カンファー、フレッシュ",
  "vocab_fr": "Herbacé, Camphré, Frais",
  "components": "1,8-シネオール、カンファー、α-ピネン",
  "sg": 0.89,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, strong herbal scent with camphoraceous tone",
  "ifra_en": "No restriction",
  "vocab_en": "Herbal, Camphor, Fresh",
  "family_detail": "Aromatic",
  "components_en": "1,8-Cineole, Camphor, alpha-Pinene"
 },
 {
  "name": "Rose wood",
  "note": "Middle",
  "family": "ウッディ",
  "desc": "リナロールを多く含む甘くフローラルなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、フローラル、スウィート",
  "vocab_fr": "Boisé, Floral, Doux",
  "components": "リナロール、α-テルピネオール",
  "sg": 0.87,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, floral woody scent rich in linalool",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Floral, Sweet",
  "family_detail": "Woody / Floral",
  "components_en": "Linalool, alpha-Terpineol"
 },
 {
  "name": "Sandal Wood",
  "note": "Base",
  "family": "ウッディ",
  "desc": "非常に柔らかく甘い、クリーミーなウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、クリーミー、ミルキー",
  "vocab_fr": "Boisé, Crémeux, Lacté",
  "components": "α-サンタロール、β-サンタロール",
  "sg": 0.95,
  "defaultDilution": 10.0,
  "desc_en": "Very soft, sweet, creamy woody scent",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Creamy, Milky",
  "family_detail": "Woody",
  "components_en": "alpha-Santalol, beta-Santalol"
 },
 {
  "name": "Seaweed abs",
  "note": "Base",
  "family": "グリーン・フルーティー",
  "desc": "強い潮の香り、オゾンや海藻のニュアンス",
  "ifra": "制限なし",
  "vocab_ja": "マリーン、オゾニック、サルティ",
  "vocab_fr": "Marin, Ozonique, Salé",
  "components": "ジメチルスルフィド、ジクチオプテレン類",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Strong salty-sea scent with ozonic seaweed nuances",
  "ifra_en": "No restriction",
  "vocab_en": "Marine, Ozonic, Salty",
  "family_detail": "Marine",
  "components_en": "Dimethyl sulfide, Dictyopterenes"
 },
 {
  "name": "Silver birch",
  "note": "Base",
  "family": "ムスク・アニマリック",
  "desc": "白樺特有の甘くウッディ、わずかにレザー調の香り",
  "ifra": "2.5 サリチル酸メチル制限",
  "vocab_ja": "ウッディ、レザー、スウィート",
  "vocab_fr": "Boisé, Cuiré, Doux",
  "components": "サリチル酸メチル、ベツレノール",
  "sg": 1.17,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, woody birch scent with a hint of leather",
  "ifra_en": "2.5% Methyl salicylate restriction",
  "vocab_en": "Woody, Leather, Sweet",
  "family_detail": "Leather / Woody",
  "components_en": "Methyl salicylate, Betulenol"
 },
 {
  "name": "Spanish sage",
  "note": "Top",
  "family": "ハーバル",
  "desc": "カンファー調でスパイシーな爽やかなハーブ香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "ハーバル、カンファー、スパイシー",
  "vocab_fr": "Herbacé, Camphré, Épicé",
  "components": "カンファー、1",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, spicy herbal scent with a camphoraceous tone",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Herbal, Camphor, Spicy",
  "family_detail": "Aromatic",
  "components_en": "Camphor, 1"
 },
 {
  "name": "Sweet birch",
  "note": "Top",
  "family": "スパイシー",
  "desc": "ウィンターグリーンに似た甘く薬効感のある香り",
  "ifra": "2.5 サリチル酸メチル制限",
  "vocab_ja": "ミント、メディシナル、スウィート",
  "vocab_fr": "Mentholé, Médicinal, Doux",
  "components": "サリチル酸メチル",
  "sg": 1.17,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, medicinal scent similar to wintergreen",
  "ifra_en": "2.5% Methyl salicylate restriction",
  "vocab_en": "Minty, Medicinal, Sweet",
  "family_detail": "Spicy / Minty",
  "components_en": "Methyl salicylate"
 },
 {
  "name": "Tea tree",
  "note": "Top",
  "family": "ハーバル",
  "desc": "フレッシュで薬効感のある強いカンファー香",
  "ifra": "制限なし",
  "vocab_ja": "カンファー、メディシナル、フレッシュ",
  "vocab_fr": "Camphré, Médicinal, Frais",
  "components": "テルピネン-4-オール、γ-テルピネン、1",
  "sg": 0.87,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, strong camphoraceous medicinal scent",
  "ifra_en": "No restriction",
  "vocab_en": "Camphor, Medicinal, Fresh",
  "family_detail": "Aromatic",
  "components_en": "Terpinen-4-ol, gamma-Terpinene, 1"
 },
 {
  "name": "Thyme",
  "note": "Top",
  "family": "ハーバル",
  "desc": "強く温かい、薬効感のあるスパイシーなハーブ香",
  "ifra": "0.7 光毒性",
  "vocab_ja": "ハーバル、スパイシー、メディシナル",
  "vocab_fr": "Herbacé, Épicé, Médicinal",
  "components": "チモール、カルバクロール、リナロール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Strong, warm, spicy medicinal herbal scent",
  "ifra_en": "0.7% Phototoxicity",
  "vocab_en": "Herbal, Spicy, Medicinal",
  "family_detail": "Aromatic / Spicy",
  "components_en": "Thymol, Carvacrol, Linalool"
 },
 {
  "name": "Tonka Bean Abs",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "バニラやアーモンドに似た甘く温かいクマリン香",
  "ifra": "1.5 クマリン制限",
  "vocab_ja": "バルサミック、スウィート、アーモンド",
  "vocab_fr": "Balsamique, Doux, Amande",
  "components": "クマリン",
  "sg": 1.1,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, warm coumarin scent like vanilla and almond",
  "ifra_en": "1.5% Coumarin restriction",
  "vocab_en": "Balsamic, Sweet, Almond",
  "family_detail": "Balsamic / Sweet",
  "components_en": "Coumarin"
 },
 {
  "name": "Tuberose Abs",
  "note": "Middle",
  "family": "フローラル",
  "desc": "非常に濃厚で甘く、重厚なホワイトフローラル香",
  "ifra": "制限なし",
  "vocab_ja": "フローラル、インテンス、ラクトニック",
  "vocab_fr": "Floral, Intense, Lacté",
  "components": "ラクトン類、アントラニル酸メチル、インドール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Very rich, sweet, heavy white floral scent",
  "ifra_en": "No restriction",
  "vocab_en": "Floral, Intense, Lactonic",
  "family_detail": "Floral",
  "components_en": "Lactones, Methyl anthranilate, Indole"
 },
 {
  "name": "Vanilla Oleoresin",
  "note": "Base",
  "family": "バルサム・レジン",
  "desc": "濃厚で甘い、典型的なバニラの香り",
  "ifra": "制限なし",
  "vocab_ja": "バルサミック、スウィート、グルマン",
  "vocab_fr": "Balsamique, Doux, Gourmand",
  "components": "バニリン、エチルバニリン",
  "sg": 1.06,
  "defaultDilution": 10.0,
  "desc_en": "Rich, sweet, classic vanilla scent",
  "ifra_en": "No restriction",
  "vocab_en": "Balsamic, Sweet, Gourmand",
  "family_detail": "Balsamic",
  "components_en": "Vanillin, Ethylvanillin"
 },
 {
  "name": "Vetiver",
  "note": "Base",
  "family": "ウッディ",
  "desc": "土っぽくスモーキーで、根の力強いウッディ香",
  "ifra": "制限なし",
  "vocab_ja": "ウッディ、アーシー、スモーキー",
  "vocab_fr": "Boisé, Terreux, Fumé",
  "components": "ベチベロール、ベチボン",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Earthy, smoky, powerful rooty woody scent",
  "ifra_en": "No restriction",
  "vocab_en": "Woody, Earthy, Smoky",
  "family_detail": "Woody / Earthy",
  "components_en": "Vetiverol, Vetivone"
 },
 {
  "name": "Violet leaf",
  "note": "Middle",
  "family": "グリーン・フルーティー",
  "desc": "きゅうりのようなみずみずしいフレッシュグリーン香",
  "ifra": "制限なし",
  "vocab_ja": "グリーン、キューカンバー、ウォータリー",
  "vocab_fr": "Vert, Concombre, Aqueux",
  "components": "ノナジエナール",
  "sg": 1.0,
  "defaultDilution": 10.0,
  "desc_en": "Fresh, watery green scent like cucumber",
  "ifra_en": "No restriction",
  "vocab_en": "Green, Cucumber, Watery",
  "family_detail": "Green",
  "components_en": "Nonadienal"
 },
 {
  "name": "Winter green",
  "note": "Top",
  "family": "スパイシー",
  "desc": "サリチル酸メチル特有の強いミント・薬効香",
  "ifra": "2.5 サリチル酸メチル制限",
  "vocab_ja": "ミント、メディシナル、シャープ",
  "vocab_fr": "Mentholé, Médicinal, Acide",
  "components": "サリチル酸メチル",
  "sg": 1.18,
  "defaultDilution": 10.0,
  "desc_en": "Strong minty medicinal scent from methyl salicylate",
  "ifra_en": "2.5% Methyl salicylate restriction",
  "vocab_en": "Minty, Medicinal, Sharp",
  "family_detail": "Spicy / Minty",
  "components_en": "Methyl salicylate"
 },
 {
  "name": "Ylang Ylang",
  "note": "Middle",
  "family": "フローラル",
  "desc": "甘くスパイシーで、非常に官能的なフローラル香",
  "ifra": "0.73 皮膚感作性",
  "vocab_ja": "フローラル、スウィート、スパイシー",
  "vocab_fr": "Floral, Doux, Épicé",
  "components": "酢酸ベンジル、リナロール、ゲルマクレンD",
  "sg": 0.98,
  "defaultDilution": 10.0,
  "desc_en": "Sweet, spicy, very sensual floral scent",
  "ifra_en": "0.73% Skin sensitization",
  "vocab_en": "Floral, Sweet, Spicy",
  "family_detail": "Floral",
  "components_en": "Benzyl acetate, Linalool, Germacrene D"
 },
 {
  "name": "Alchol",
  "note": "-",
  "family": "その他",
  "desc": "香水用アルコール。無臭に近いが揮発時に特有の匂い。",
  "ifra": "制限なし",
  "vocab_ja": "アルコール、ニュートラル、ソルベント",
  "vocab_fr": "Alcool, Neutre, Solvant",
  "components": "エタノール",
  "sg": 0.798,
  "defaultDilution": 10.0,
  "desc_en": "Perfumery alcohol. Nearly odorless but has a distinct scent on evaporation.",
  "ifra_en": "No restriction",
  "vocab_en": "Alcohol, Neutral, Solvent",
  "family_detail": "Solvent (溶剤)",
  "components_en": "Ethanol"
 }
];
